version: "3.3"
services:
  mongo:
    image: mongo
    container_name: "tipon-mongo"
    restart: always
    ports:
      - "27017:27017"
  tips_server:
    container_name: "tips-server"
    restart: always
    build: "./tips"
    environment:
      - TIPON_TIPS_PORT=8000
      - TIPON_MONGO_HOST=mongo
      - TIPON_MONGO_PORT=27017
    ports:
      - "8000:8000"
    depends_on:
      - "mongo"
