version: "3.3"
services:
  mongo:
    image: mongo
    container_name: "tipon-mongo"
    restart: always
    ports:
      - "27017:27017"
  tips:
    container_name: "tips-server"
    restart: always
    build: "./tips"
    ports:
      - "8000:8000"
    depends_on:
      - "mongo"
