version: "3.3"
services:
  mongo:
    image: mongo
    container_name: "tipon-mongo"
    restart: always
    ports:
      - "27017:27017"
  users_server:
    container_name: "users-server"
    restart: always
    build: "./users"
    environment:
      - TIPON_USERS_PORT=5000
      - TIPON_MONGO_HOST=mongo
      - TIPON_MONGO_PORT=27017
    ports:
      - "5000:5000"
    depends_on:
      - "mongo"
  users_api:
    container_name: "users-api"
    restart: always
    build: ./users-api
    ports:
      - "5001:5001"
    depends_on:
      - "users_server"
  tips_server:
    container_name: "tips-server"
    restart: always
    build: "./tips"
    environment:
      - TIPON_TIPS_PORT=8000
      - TIPON_MONGO_HOST=mongo
      - TIPON_MONGO_PORT=27017
    ports:
      - "8000:8000"
    depends_on:
      - "mongo"
  tips_api:
    container_name: "tips-api"
    restart: always
    build: ./tips-api
    ports:
      - "8001:8001"
    depends_on:
      - "tips_server"