// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.6
// source: pb/tip.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tip struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Amount int64  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Note   string `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"`
	UserId string `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *Tip) Reset() {
	*x = Tip{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_tip_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tip) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tip) ProtoMessage() {}

func (x *Tip) ProtoReflect() protoreflect.Message {
	mi := &file_pb_tip_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tip.ProtoReflect.Descriptor instead.
func (*Tip) Descriptor() ([]byte, []int) {
	return file_pb_tip_proto_rawDescGZIP(), []int{0}
}

func (x *Tip) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tip) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Tip) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *Tip) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type FindTipsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FindTipsRequest) Reset() {
	*x = FindTipsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_tip_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindTipsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindTipsRequest) ProtoMessage() {}

func (x *FindTipsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_tip_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindTipsRequest.ProtoReflect.Descriptor instead.
func (*FindTipsRequest) Descriptor() ([]byte, []int) {
	return file_pb_tip_proto_rawDescGZIP(), []int{1}
}

type FindOneTipRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *FindOneTipRequest) Reset() {
	*x = FindOneTipRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_tip_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindOneTipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindOneTipRequest) ProtoMessage() {}

func (x *FindOneTipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_tip_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindOneTipRequest.ProtoReflect.Descriptor instead.
func (*FindOneTipRequest) Descriptor() ([]byte, []int) {
	return file_pb_tip_proto_rawDescGZIP(), []int{2}
}

func (x *FindOneTipRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateTipRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Amount int64  `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Note   string `protobuf:"bytes,2,opt,name=note,proto3" json:"note,omitempty"`
	UserId string `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *CreateTipRequest) Reset() {
	*x = CreateTipRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_tip_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTipRequest) ProtoMessage() {}

func (x *CreateTipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_tip_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTipRequest.ProtoReflect.Descriptor instead.
func (*CreateTipRequest) Descriptor() ([]byte, []int) {
	return file_pb_tip_proto_rawDescGZIP(), []int{3}
}

func (x *CreateTipRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateTipRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *CreateTipRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UpdateTipRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *UpdateTipRequest) Reset() {
	*x = UpdateTipRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_tip_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTipRequest) ProtoMessage() {}

func (x *UpdateTipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_tip_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTipRequest.ProtoReflect.Descriptor instead.
func (*UpdateTipRequest) Descriptor() ([]byte, []int) {
	return file_pb_tip_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateTipRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_pb_tip_proto protoreflect.FileDescriptor

var file_pb_tip_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x70, 0x62, 0x2f, 0x74, 0x69, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02,
	0x70, 0x62, 0x22, 0x5a, 0x0a, 0x03, 0x54, 0x69, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x6f, 0x74, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x11,
	0x0a, 0x0f, 0x46, 0x69, 0x6e, 0x64, 0x54, 0x69, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x23, 0x0a, 0x11, 0x46, 0x69, 0x6e, 0x64, 0x4f, 0x6e, 0x65, 0x54, 0x69, 0x70, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x57, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x54, 0x69, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22,
	0x22, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x70, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x32, 0xc6, 0x01, 0x0a, 0x0a, 0x54, 0x69, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x2c, 0x0a, 0x08, 0x46, 0x69, 0x6e, 0x64, 0x54, 0x69, 0x70, 0x73, 0x12, 0x13,
	0x2e, 0x70, 0x62, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x54, 0x69, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x07, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x69, 0x70, 0x22, 0x00, 0x30, 0x01,
	0x12, 0x2e, 0x0a, 0x0a, 0x46, 0x69, 0x6e, 0x64, 0x4f, 0x6e, 0x65, 0x54, 0x69, 0x70, 0x12, 0x15,
	0x2e, 0x70, 0x62, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x4f, 0x6e, 0x65, 0x54, 0x69, 0x70, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x07, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x69, 0x70, 0x22, 0x00,
	0x12, 0x2c, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x70, 0x12, 0x14, 0x2e,
	0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x70, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x07, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x69, 0x70, 0x22, 0x00, 0x12, 0x2c,
	0x0a, 0x09, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x70, 0x12, 0x14, 0x2e, 0x70, 0x62,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x07, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x69, 0x70, 0x22, 0x00, 0x42, 0x1e, 0x5a, 0x1c,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x78, 0x38, 0x2f, 0x74,
	0x69, 0x70, 0x6f, 0x6e, 0x2f, 0x74, 0x69, 0x70, 0x73, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_tip_proto_rawDescOnce sync.Once
	file_pb_tip_proto_rawDescData = file_pb_tip_proto_rawDesc
)

func file_pb_tip_proto_rawDescGZIP() []byte {
	file_pb_tip_proto_rawDescOnce.Do(func() {
		file_pb_tip_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_tip_proto_rawDescData)
	})
	return file_pb_tip_proto_rawDescData
}

var file_pb_tip_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pb_tip_proto_goTypes = []interface{}{
	(*Tip)(nil),               // 0: pb.Tip
	(*FindTipsRequest)(nil),   // 1: pb.FindTipsRequest
	(*FindOneTipRequest)(nil), // 2: pb.FindOneTipRequest
	(*CreateTipRequest)(nil),  // 3: pb.CreateTipRequest
	(*UpdateTipRequest)(nil),  // 4: pb.UpdateTipRequest
}
var file_pb_tip_proto_depIdxs = []int32{
	1, // 0: pb.TipService.FindTips:input_type -> pb.FindTipsRequest
	2, // 1: pb.TipService.FindOneTip:input_type -> pb.FindOneTipRequest
	3, // 2: pb.TipService.CreateTip:input_type -> pb.CreateTipRequest
	4, // 3: pb.TipService.UpdateTip:input_type -> pb.UpdateTipRequest
	0, // 4: pb.TipService.FindTips:output_type -> pb.Tip
	0, // 5: pb.TipService.FindOneTip:output_type -> pb.Tip
	0, // 6: pb.TipService.CreateTip:output_type -> pb.Tip
	0, // 7: pb.TipService.UpdateTip:output_type -> pb.Tip
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_tip_proto_init() }
func file_pb_tip_proto_init() {
	if File_pb_tip_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_tip_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tip); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_tip_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindTipsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_tip_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindOneTipRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_tip_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTipRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_tip_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateTipRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_tip_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_tip_proto_goTypes,
		DependencyIndexes: file_pb_tip_proto_depIdxs,
		MessageInfos:      file_pb_tip_proto_msgTypes,
	}.Build()
	File_pb_tip_proto = out.File
	file_pb_tip_proto_rawDesc = nil
	file_pb_tip_proto_goTypes = nil
	file_pb_tip_proto_depIdxs = nil
}
